# -*- coding: utf-8 -*-
"""PLR2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12aBHAtFtHlTZi3DVDYh1vcIRGEYK5RvO
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.neighbors import NearestNeighbors
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score

print("All libraries imported successfully!")

from google.colab import files

uploaded = files.upload()

file_name = list(uploaded.keys())[0]

print("Uploaded file:", file_name)

df = pd.read_excel(file_name)

print("Dataset loaded successfully!")

print("Number of rows:", df.shape[0])
print("Number of columns:", df.shape[1])

display(df.head())

print("Column Names:")
print(df.columns.tolist())

print("\nDataset Shape:")
print(df.shape)

print("\nData Types:")
print(df.dtypes)

print("Missing Values in Each Column:")

display(df.isnull().sum().to_frame("Missing Values"))

text_cols = [
    "Learning History",
    "Skill Gap",
    "Career Goal",
    "Requirement Type",
    "Current Level"
]

num_cols = [
    "CGPA",
    "Assessment Score",
    "Time Available (hrs/day)",
    "Attendance (%)"
]

# Text columns
for col in text_cols:
    df[col] = df[col].fillna("Unknown").astype(str)

# Numerical columns
for col in num_cols:
    df[col] = pd.to_numeric(df[col], errors="coerce")
    df[col] = df[col].fillna(df[col].median())

print("Data cleaning completed!")
print("Total missing values:", df.isnull().sum().sum())

df["Student_Profile"] = (
    df["Learning History"] + " " +
    df["Skill Gap"] + " " +
    df["Career Goal"] + " " +
    df["Current Level"] + " " +
    df["Requirement Type"]
)

print("Student learning profile created!")

display(
    df[
        [
            "Student ID",
            "Student Name",
            "Skill Gap",
            "Career Goal",
            "Student_Profile"
        ]
    ].head()
)

tfidf = TfidfVectorizer(
    stop_words="english",
    ngram_range=(1, 2)
)

X_text = tfidf.fit_transform(df["Student_Profile"])

print("TF-IDF completed!")

print("TF-IDF Matrix Shape:")
print(X_text.shape)

print(
    "Number of text features:",
    len(tfidf.get_feature_names_out())
)

knn = NearestNeighbors(
    n_neighbors=5,
    metric="cosine"
)

knn.fit(X_text)

distances, indices = knn.kneighbors(X_text)

print("KNN model trained successfully!")
print("5 similar students can be found for every student.")

student_index = 0

similar_students = indices[student_index][1:]

print(
    "Selected Student:",
    df.loc[student_index, "Student Name"]
)

print("\nSimilar Students:")

display(
    df.loc[
        similar_students,
        [
            "Student ID",
            "Student Name",
            "Skill Gap",
            "Career Goal",
            "Current Level"
        ]
    ]
)

cluster_columns = [
    "CGPA",
    "Assessment Score",
    "Time Available (hrs/day)",
    "Attendance (%)"
]

scaler = StandardScaler()

X_numeric = scaler.fit_transform(
    df[cluster_columns]
)

print("Numerical features standardized!")

kmeans = KMeans(
    n_clusters=3,
    random_state=42,
    n_init=10
)

df["Learning_Profile_Cluster"] = kmeans.fit_predict(
    X_numeric
)

print("K-Means model trained successfully!")

display(
    df["Learning_Profile_Cluster"]
    .value_counts()
    .sort_index()
    .to_frame("Number of Students")
)

silhouette = silhouette_score(
    X_numeric,
    df["Learning_Profile_Cluster"]
)

print(
    "Silhouette Score:",
    round(silhouette, 3)
)

recommendation_map = {

    "machine learning": (
        "Machine Learning with Python",
        "Student Performance Prediction System"
    ),

    "python": (
        "Python Programming for Data Science",
        "Student Result Analysis using Python"
    ),

    "data analysis": (
        "Data Analytics with Python, Pandas & Power BI",
        "Student Performance Analytics Dashboard"
    ),

    "sql": (
        "SQL and Database Analytics",
        "Student Database Management & Analysis"
    ),

    "cybersecurity": (
        "Cyber Security Fundamentals",
        "Basic Network Security Assessment"
    ),

    "cyber security": (
        "Cyber Security Fundamentals",
        "Basic Network Security Assessment"
    ),

    "web development": (
        "Full Stack Web Development",
        "Student Learning Portal"
    ),

    "cloud computing": (
        "Cloud Computing Fundamentals",
        "Deploy a Student Analytics App on Cloud"
    ),

    "deep learning": (
        "Deep Learning with TensorFlow/PyTorch",
        "Image Classification using Neural Networks"
    ),

    "statistics": (
        "Statistics for Data Science",
        "Statistical Analysis of Student Performance"
    ),

    "data structures": (
        "Data Structures & Algorithms",
        "Algorithm Visualizer"
    ),

    "programming fundamentals": (
        "Programming Fundamentals with Python",
        "Beginner Coding Practice & Mini Application"
    ),

    "computer basics": (
        "Computer Fundamentals",
        "Personal Computer Skills Portfolio"
    )
}

print("Recommendation database created!")
print("Total skill areas:", len(recommendation_map))

def find_best_topic(
    skill_gap,
    career_goal,
    learning_history
):

    text = (
        str(skill_gap) + " " +
        str(career_goal) + " " +
        str(learning_history)
    ).lower()

    # Match skill gap
    for key in sorted(
        recommendation_map,
        key=len,
        reverse=True
    ):

        if key in text:
            return key

    # Career-based fallback
    if "data scientist" in text:
        return "machine learning"

    if "data analyst" in text:
        return "data analysis"

    if "developer" in text:
        return "web development"

    return "python"

def calculate_study_hours(row):

    available_hours = float(
        row["Time Available (hrs/day)"]
    )

    assessment = float(
        row["Assessment Score"]
    )

    level = str(
        row["Current Level"]
    ).lower()

    # Beginner / weak score
    if "beginner" in level or assessment < 50:

        fraction = 0.60

    # Intermediate
    elif assessment < 70:

        fraction = 0.75

    # Good performance
    else:

        fraction = 0.90

    hours = (
        available_hours *
        fraction
    )

    # Round to half hour
    hours = round(
        hours * 2
    ) / 2

    hours = max(
        0.5,
        hours
    )

    hours = min(
        available_hours,
        hours
    )

    return hours

def recommend_student(row):

    topic = find_best_topic(
        row["Skill Gap"],
        row["Career Goal"],
        row["Learning History"]
    )

    course, project = recommendation_map[
        topic
    ]

    study_hours = calculate_study_hours(
        row
    )

    return pd.Series({

        "Recommended Skill Area":
            topic.title(),

        "Recommended Course":
            course,

        "Recommended Project":
            project,

        "Suggested Daily Study Hours":
            study_hours
    })

recommendations = df.apply(
    recommend_student,
    axis=1
)

df_final = pd.concat(
    [
        df,
        recommendations
    ],
    axis=1
)

print(
    "Recommendations generated for all students!"
)

display(
    df_final[
        [
            "Student ID",
            "Student Name",
            "Skill Gap",
            "Career Goal",
            "Recommended Course",
            "Recommended Project",
            "Suggested Daily Study Hours"
        ]
    ].head(10)
)

student_index = 7

student = df_final.iloc[
    student_index
]

print("================================")
print("STUDENT RECOMMENDATION")
print("================================")

print(
    "Student Name:",
    student["Student Name"]
)

print(
    "Learning History:",
    student["Learning History"]
)

print(
    "Skill Gap:",
    student["Skill Gap"]
)

print(
    "Career Goal:",
    student["Career Goal"]
)

print(
    "Current Level:",
    student["Current Level"]
)

print(
    "\nRecommended Skill:",
    student["Recommended Skill Area"]
)

print(
    "Recommended Course:",
    student["Recommended Course"]
)

print(
    "Recommended Project:",
    student["Recommended Project"]
)

print(
    "Suggested Daily Study Hours:",
    student["Suggested Daily Study Hours"]
)

student_index = 9

similar_indexes = indices[
    student_index
][1:]

print(
    "Selected Student:",
    df.loc[
        student_index,
        "Student Name"
    ]
)

print("\nSimilar Students:")

display(
    df.loc[
        similar_indexes,
        [
            "Student ID",
            "Student Name",
            "Skill Gap",
            "Career Goal",
            "Current Level"
        ]
    ]
)

output_columns = [

    "Student ID",
    "Student Name",
    "College",
    "Branch",
    "Year",

    "CGPA",
    "Learning History",
    "Skill Gap",
    "Career Goal",

    "Assessment Score",
    "Time Available (hrs/day)",
    "Attendance (%)",

    "Requirement Type",
    "Current Level",

    "Learning_Profile_Cluster",

    "Recommended Skill Area",
    "Recommended Course",
    "Recommended Project",
    "Suggested Daily Study Hours"
]

final_output = df_final[
    output_columns
].copy()

output_file = (
    "PLR2_Final_Course_Recommendations.xlsx"
)

final_output.to_excel(
    output_file,
    index=False
)

print("Final Excel file created!")
print(
    "Total students:",
    len(final_output)
)

display(
    final_output.head(10)
)

from google.colab import files

files.download(
    "PLR2_Final_Course_Recommendations.xlsx"
)

new_student = pd.DataFrame({

    "Learning History": [
        "Excel , pyton"
    ],

    "Skill Gap": [
        "SQL, PowerBI"
    ],

    "Career Goal": [
        "Data Analyst"
    ],

    "Current Level": [
        "Intermediate"
    ],

    "Requirement Type": [
        "Complete Beginner"
    ],

    "Assessment Score": [
        20
    ],

    "Time Available (hrs/day)": [
        8
    ],

    "CGPA": [
        6.6
    ],

    "Attendance (%)": [
        20
    ]
})

new_recommendation = recommend_student(
    new_student.iloc[0]
)

print("================================")
print("NEW STUDENT PREDICTION")
print("================================")

print(
    "Recommended Skill:",
    new_recommendation[
        "Recommended Skill Area"
    ]
)

print(
    "Recommended Course:",
    new_recommendation[
        "Recommended Course"
    ]
)

print(
    "Recommended Project:",
    new_recommendation[
        "Recommended Project"
    ]
)

print(
    "Suggested Daily Hours:",
    new_recommendation[
        "Suggested Daily Study Hours"
    ]
)

from google.colab import files

uploaded = files.upload()

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score


quiz_file = "Beginner_Quiz.xlsx"

quiz_df = pd.read_excel(
    quiz_file,
    sheet_name="Beginner_Quiz"
)

print("Quiz loaded successfully!")
print("Number of questions:", len(quiz_df))



features = [
    "problem_solving",
    "design_interest",
    "math_interest",
    "web_interest",
    "data_interest",
    "programming_interest",
    "app_interest",
    "analytical_thinking",
    "computer_interest",
    "communication_interest"
]



answer_feature_map = {

    1: {
        "A": ["problem_solving"],
        "B": ["design_interest"],
        "C": ["data_interest"],
        "D": ["problem_solving", "programming_interest"]
    },

    2: {
        "A": ["analytical_thinking"],
        "B": ["design_interest", "web_interest"],
        "C": ["programming_interest"],
        "D": ["communication_interest"]
    },

    3: {
        "A": ["math_interest"],
        "B": ["computer_interest"],
        "C": ["design_interest"],
        "D": ["communication_interest"]
    },

    4: {
        "A": ["analytical_thinking", "data_interest"],
        "B": ["web_interest"],
        "C": ["app_interest", "design_interest"],
        "D": ["problem_solving", "programming_interest"]
    },

    5: {
        "A": ["data_interest", "analytical_thinking"],
        "B": ["web_interest"],
        "C": ["app_interest", "programming_interest"],
        "D": ["design_interest"]
    },

    6: {
        "A": ["math_interest"],
        "B": ["computer_interest", "programming_interest"],
        "C": ["design_interest"],
        "D": ["communication_interest"]
    },

    7: {
        "A": ["analytical_thinking", "problem_solving"],
        "B": ["problem_solving"],
        "C": ["design_interest"],
        "D": ["communication_interest"]
    },

    8: {
        "A": ["data_interest", "analytical_thinking"],
        "B": ["web_interest"],
        "C": ["app_interest", "programming_interest"],
        "D": ["design_interest"]
    },

    9: {
        "A": ["data_interest", "analytical_thinking"],
        "B": ["web_interest"],
        "C": ["design_interest"],
        "D": ["programming_interest"]
    },

    10: {
        "A": ["problem_solving"],
        "B": ["design_interest"],
        "C": ["programming_interest"],
        "D": ["analytical_thinking", "data_interest"]
    }
}


training_data = [

    # problem, design, math, web, data, programming,
    # app, analytical, computer, communication, career

    [5, 0, 4, 0, 5, 3, 1, 5, 3, 1, "Data Science"],
    [4, 0, 5, 0, 5, 4, 1, 5, 4, 1, "Machine Learning"],
    [3, 0, 3, 5, 2, 5, 3, 3, 5, 1, "Web Development"],
    [2, 5, 1, 4, 1, 2, 3, 2, 2, 2, "UI/UX Design"],
    [1, 5, 2, 3, 1, 1, 2, 1, 2, 4, "UI/UX Design"],
    [4, 1, 3, 5, 2, 5, 4, 4, 5, 1, "Web Development"],
    [5, 1, 5, 1, 5, 5, 1, 5, 5, 1, "Machine Learning"],
    [3, 2, 2, 4, 2, 4, 5, 3, 5, 1, "App Development"],
    [2, 5, 2, 3, 1, 2, 4, 2, 2, 5, "UI/UX Design"],
    [4, 0, 4, 1, 5, 4, 1, 5, 4, 2, "Data Science"],
    [4, 1, 3, 5, 2, 5, 2, 4, 5, 1, "Web Development"],
    [1, 5, 1, 2, 1, 1, 3, 1, 1, 5, "UI/UX Design"],
    [5, 0, 5, 0, 4, 5, 1, 5, 5, 1, "Machine Learning"],
    [2, 1, 3, 4, 2, 4, 5, 3, 5, 2, "App Development"],
    [3, 4, 2, 3, 2, 2, 4, 2, 2, 4, "UI/UX Design"],
    [4, 1, 4, 4, 4, 4, 2, 4, 5, 1, "Data Science"],
    [3, 1, 2, 5, 1, 5, 3, 3, 5, 1, "Web Development"],
    [2, 4, 2, 3, 1, 2, 4, 2, 2, 5, "UI/UX Design"],
    [5, 0, 5, 1, 5, 5, 1, 5, 5, 1, "Machine Learning"],
    [2, 1, 3, 3, 1, 4, 5, 2, 5, 2, "App Development"]
]

training_columns = features + ["Recommended_Path"]

training_df = pd.DataFrame(
    training_data,
    columns=training_columns
)



X = training_df[features]
y = training_df["Recommended_Path"]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.25,
    random_state=42,
    stratify=y
)

model = RandomForestClassifier(
    n_estimators=200,
    random_state=42
)

model.fit(X_train, y_train)


y_pred = model.predict(X_test)

accuracy = accuracy_score(
    y_test,
    y_pred
)

print("\n" + "=" * 60)
print("ML MODEL TRAINED")
print("=" * 60)

print("Model Accuracy:", round(accuracy * 100, 2), "%")



print("\n")
print("=" * 60)
print("        BEGINNER CAREER RECOMMENDATION QUIZ")
print("=" * 60)

print("\nAnswer all questions using A, B, C or D.")


# Initialize student features

student_features = {
    feature: 0
    for feature in features
}



for index, row in quiz_df.iterrows():

    question_number = index + 1

    print("\n" + "-" * 60)

    print(
        f"Q{question_number}. "
        + str(row["Question"])
    )

    print(
        "A.",
        row["Answer_A"]
    )

    print(
        "B.",
        row["Answer_B"]
    )

    print(
        "C.",
        row["Answer_C"]
    )

    print(
        "D.",
        row["Answer_D"]
    )

    answer = input(
        "\nYour answer (A/B/C/D): "
    ).strip().upper()

    while answer not in ["A", "B", "C", "D"]:

        print(
            "Invalid answer. Please enter A, B, C or D."
        )

        answer = input(
            "Your answer (A/B/C/D): "
        ).strip().upper()



    selected_features = answer_feature_map[
        question_number
    ][answer]


    for feature in selected_features:

        if feature in student_features:

            student_features[feature] += 1



print("\n")
print("=" * 60)
print("             YOUR FEATURE PROFILE")
print("=" * 60)

for feature, value in student_features.items():

    print(
        f"{feature:25s}: {value}"
    )



student_input = pd.DataFrame(
    [
        [
            student_features[feature]
            for feature in features
        ]
    ],
    columns=features
)


print("\n")
print("=" * 60)
print("              ML INPUT")
print("=" * 60)

print(student_input)



prediction = model.predict(
    student_input
)

recommended_path = prediction[0]



probabilities = model.predict_proba(
    student_input
)[0]

class_names = model.classes_

probability_df = pd.DataFrame({
    "Career_Path": class_names,
    "Probability": probabilities
})

probability_df = probability_df.sort_values(
    "Probability",
    ascending=False
)



print("\n")
print("=" * 60)
print("          YOUR RECOMMENDED LEARNING PATH")
print("=" * 60)

print(
    "\nRecommended Path:",
    recommended_path
)

print(
    "\nRecommendation probabilities:"
)

for _, row in probability_df.iterrows():

    print(
        f"{row['Career_Path']:25s} "
        f"{row['Probability'] * 100:.2f}%"
    )



roadmaps = {

    "Web Development": [
        "HTML",
        "CSS",
        "JavaScript",
        "Git & GitHub",
        "React",
        "Backend Development"
    ],

    "Data Science": [
        "Python",
        "NumPy",
        "Pandas",
        "Matplotlib",
        "Statistics",
        "Machine Learning"
    ],

    "Machine Learning": [
        "Python",
        "NumPy",
        "Pandas",
        "Statistics",
        "Scikit-learn",
        "Machine Learning Projects"
    ],

    "UI/UX Design": [
        "Design Principles",
        "Figma",
        "Wireframing",
        "Prototyping",
        "User Research",
        "UI/UX Projects"
    ],

    "App Development": [
        "Programming Basics",
        "UI Design",
        "Android/Flutter",
        "APIs",
        "Database Basics",
        "Mobile App Projects"
    ]
}


print("\n")
print("=" * 60)
print("              SUGGESTED LEARNING ROADMAP")
print("=" * 60)

if recommended_path in roadmaps:

    for number, topic in enumerate(
        roadmaps[recommended_path],
        start=1
    ):

        print(
            f"{number}. {topic}"
        )

print("\nQuiz completed successfully!")